language: scala
# This is a workaround for this issue: https://goo.gl/FexVa7
addons:
  hostname: short-hostname
matrix:
  include:
   - scala: 2.12.1
     env: JDK=oraclejdk8
   - scala: 2.11.8
     env: JDK=openjdk6
notifications:
  email:
    recipients:
    - lance.gatlin@s-mach.net
script:
 # Fix issue where JDK env from matrix above not picked up by travis
 - jdk_switcher use $JDK
 # Use plz instead of ++ from sbt-doge plugin to respect subproject crossScalaVersions
 - sbt clean coverage "plz $TRAVIS_SCALA_VERSION test"  -J-Xmx4g
after_success:
 # bug where need to run this twice for coverage to work
 # https://github.com/kamilkloch/scoverage-multi-module
 - sbt coverage "plz $TRAVIS_SCALA_VERSION test" coverageReport  -J-Xmx4g
 - sbt coverageReport
 - sbt coverageAggregate
 - sbt coveralls
 - sbt codacyCoverage
 - >
      test "${TRAVIS_PULL_REQUEST}" = 'false' &&
      test "${TRAVIS_BRANCH}" == 'master' &&
      test "${TRAVIS_JDK_VERSION}" = 'openjdk6' &&
      sbt 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("SONATYPE_USER"), System.getenv("SONATYPE_PASS"))' publish
